general:
  startup_commands:
    - 'shell-exec zebar'
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: false
    trigger: 'monitor_focus'
  hide_method: 'hide'
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  inner_gap: '0px'
  outer_gap:
    top: '40px'
    right: '0px'
    bottom: '0px'
    left: '0px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#000000'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: true
      opacity: '100%'
  other_windows:
    border:
      enabled: true
      color: '#000000'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: true
      opacity: '100%'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: '1'
    display_name: '1'
  - name: '2'
    display_name: '2'
  - name: '3'
    display_name: '3'
  - name: '4'
    display_name: '4'
  - name: '5'
    display_name: '5'

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }
      - window_process: { equals: 'TeraCopy' }
      - window_process: { equals: 'AIMP' }
      - window_process: { equals: 'xdm' }
      - window_process: { equals: 'notepad' }
      - window_process: { equals: 'SnippingTool' }
      - window_process: { equals: 'vlc' }

keybindings:
  - commands: ['focus --direction left']
    bindings: ['alt+j']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+i']
  - commands: ['focus --direction down']
    bindings: ['alt+k']

  - commands: ['move --direction left']
    bindings: ['alt+shift+j']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+i']
  - commands: ['move --direction down']
    bindings: ['alt+shift+k']

  - commands: ['resize --width -1%']
    bindings: ['alt+r+j']
  - commands: ['resize --width +1%']
    bindings: ['alt+r+l']
  - commands: ['resize --height +1%']
    bindings: ['alt+r+k']
  - commands: ['resize --height -1%']
    bindings: ['alt+r+i']

  - commands: ['wm-toggle-pause']
    bindings: ['alt+shift+p']

  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']

  - commands: ['toggle-minimized']
    bindings: ['alt+m']

  - commands: ['close']
    bindings: ['alt+shift+q']

  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  - commands: ['wm-reload-config']
    bindings: ['alt+shift+a']

  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  - commands: ['shell-exec cmd']
    bindings: ['alt+enter']

  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']

  - commands: ['move --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5']
    bindings: ['alt+shift+5']
